### ISSUE TITLE
.getAgGridData() returns data only for those columns which are visible in viewport

### ISSUE THREAD

**Issue by elkemper** [kpmck/cypress-ag-grid#11]
When i'm trying to get data from table, it returns not full object with all columns data, but only those props, which columns are visible in viewport.
Unfortunately I can't provide any code except 
``` 
cy.get('div.ag-theme-alpine').getAgGridData().then(data=>{
      cy.log(JSON.stringify(data))
    })
```
and when i'm not stretching the viewport on cypress to fit all the columns - it returns only part of the data from the table. If I use example from the documentation it will look like:
```
[
    { "Year": "2020", "Make": "Toyota"},
    { "Year": "2020", "Make": "Ford"},
    { "Year": "2020", "Make": "Porsche" },
    { "Year": "2020", "Make": "BMW"},
    { "Year": "2020", "Make": "Mercedes" },
]
```
or if I scroll to the right:
```
[
    { "Make": "Toyota", "Model": "Celica" },
    { "Make": "Ford", "Model": "Mondeo" },
    { "Make": "Porsche", "Model": "Boxter" },
    { "Make": "BMW", "Model": "3-series" },
    { "Make": "Mercedes", "Model": "GLC300" },
]
```
When i'm waiting for whole data
```
[
    { "Year": "2020", "Make": "Toyota", "Model": "Celica" },
    { "Year": "2020", "Make": "Ford", "Model": "Mondeo" },
    { "Year": "2020", "Make": "Porsche", "Model": "Boxter" },
    { "Year": "2020", "Make": "BMW", "Model": "3-series" },
    { "Year": "2020", "Make": "Mercedes", "Model": "GLC300" },
]
```

**Comment by kpmck** [comment]
This is expected behavior due to the nature of Ag Grid. With Ag Grid, only the visible columns/rows are accessible from the DOM, so workarounds are needed to get all the information in the grid. This is outlined in the section **Limitations** section of the documentation with an example of how to overcome this issue: https://github.com/kpmck/cypress-ag-grid#limitations

Basically, you have two options:

1. You can add code to the implementation of Ag Grid in your front end project that checks if cypress is executing the tests, then show all grid content if so. This is outlined with an example in the Limitations section of the documentation: https://github.com/kpmck/cypress-ag-grid#limitations
2. Or right before grabbing the data from your grid, expand the viewport size large enough to show all the cell’s contents.

I hope that helps!

**Comment by elkemper** [comment]
Ok, thanks @kpmck  I get it. Then i'll try this workarounds. Thanks.

**Comment by kpmck** [comment]
Sounds good! Let me know if any additional assistance is needed.

**Comment by wandering-tales** [comment]
This issue is caused by AgGrid [DOM Virtualisation](https://www.ag-grid.com/react-data-grid/dom-virtualisation/) feature, which lets both columns and rows to be lazily rendered on scroll events with the aim of improving rendering performance. Unfortunately, that causes a lot of troubles during automated testing.

Attempts of programmatically scrolling the table body viewport and putting the right assertion to wait for the desired column to be visible, have always lead me to flaky tests. I have played with both scroll easing animation and duration with the only result of mitigating the issue, but never fully solve that.

The workaround I have used in a React project I currently work on, consists in explicitly suppressing the [DOM Virtualisation](https://www.ag-grid.com/react-data-grid/dom-virtualisation/) feature when Cypress is running.

To achieve that, I have set a `suppressAgGridDOMVirtualisation` flag in my `App.jsx` as follows:

```javascript
if (window.Cypress) {
  window.suppressAgGridDOMVirtualisation = true
}
```

Then, I have used the above flag to properly initialize my `AgGridReact` component by setting both the `suppressColumnVirtualisation` and `suppressRowVirtualisation` properties (see [Suppress Virtualisation](https://www.ag-grid.com/react-data-grid/dom-virtualisation/#suppress-virtualisation)):

```jsx
<AgGridReact
  {...otherProps}
  suppressColumnVirtualisation={
    window.suppressAgGridDOMVirtualisation ?? false
  }
  suppressRowVirtualisation={
    window.suppressAgGridDOMVirtualisation ?? false
  }
/>
```

All flakiness has gone away.
