### ISSUE TITLE
Question - How does 'In range' work?

### ISSUE THREAD

**Issue by gdeo** [kpmck/cypress-ag-grid#38]
For the filter condition 'In range' how should the filterValue look like, since there'll have to be 2 values entered in the From and To textboxes? Could you post an example? Thank you!

**Comment by kpmck** [comment]
There isn't an explicit command to clear the filter, but if you would like to clear a text filter, one workaround is doing the following:

```javascript
      cy.get(agGridSelector).agGridColumnFilterTextMenu({
        searchCriteria: {
          columnName: "Price",
          filterValue: "{backspace}",
          searchInputIndex: 0,
        },
        hasApplyButton: true,
      });  
```

By passing in `{backspace}` as the value, Cypress will treat it as typing backspace. The plugin already clears out the field, so then when you apply the filter, your grid should re-render with all the data instead of just the filtered data.

Clearing a checkbox would need a separate PR. Please feel free to open a feature request if this is something that is important for your workflow.

**Comment by kpmck** [comment]
There is an option you can pass called `searchInputIndex` which should help with this. You can read about that [here](https://github.com/kpmck/cypress-ag-grid#filterby-text---floating-filter). Please let me know if that does not work for you.

**Comment by gdeo** [comment]
Awesome! This worked! Thank you.
