### ISSUE TITLE
Question - Is there a way to reset the filters?

### ISSUE THREAD

**Issue by gdeo** [kpmck/cypress-ag-grid#39]
Couldn't find a way to reset the filters, is there something already added?

**Comment by kpmck** [comment]
There isn't an explicit command to clear the filter, but if you would like to clear a text filter, one workaround is doing the following:

```javascript
      cy.get(agGridSelector).agGridColumnFilterTextMenu({
        searchCriteria: {
          columnName: "Price",
          filterValue: "{backspace}",
          searchInputIndex: 0,
        },
        hasApplyButton: true,
      });  
```

By passing in `{backspace}` as the value, Cypress will treat it as typing backspace. The plugin already clears out the field, so then when you apply the filter, your grid should re-render with all the data instead of just the filtered data.

Clearing a checkbox would need a separate PR. Please feel free to open a feature request if this is something that is important for your workflow.
